In [1]:
import pandas as pd

In [2]:
application_df = pd.read_csv("application_record.csv")
credit_df = pd.read_csv("credit_record.csv")

In [3]:
application_df.head()

,ID,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,DAYS_BIRTH,DAYS_EMPLOYED,FLAG_MOBIL,FLAG_WORK_PHONE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS
0,5008804,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,NaN,2
1,5008805,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,NaN,2
2,5008806,M,Y,Y,0,112500.0,Working,Secondary / secondary special,Married,House / apartment,-21474,-1134,1,0,0,0,Security staff,2
3,5008808,F,N,Y,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,-19110,-3051,1,0,1,1,Sales staff,1
4,5008809,F,N,Y,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,-19110,-3051,1,0,1,1,Sales staff,1

In [4]:
credit_df.head()

        ID  MONTHS_BALANCE STATUS
0  5001711               0      X
1  5001711              -1      0
2  5001711              -2      0
3  5001711              -3      0
4  5001712               0      C

In [8]:
print(application_df.duplicated().sum())
print(credit_df.duplicated().sum())

0
0

In [14]:
application_df.drop_duplicates(inplace=True)
credit_df.drop_duplicates(inplace=True)

In [10]:
print(application_df.duplicated().sum())
print(credit_df.duplicated().sum())

0
0

In [12]:
application_df.to_csv("application_record_clean.csv", index=False)
credit_df.to_csv("credit_record_clean.csv", index=False)

In [ ]:
print(application_df.shape)
print(credit_df.shape)

(438557, 18)
(1048575, 3)

In [13]:
print("Duplicate records removed successfully.")

Duplicate records removed successfully.